# Docker Compose Override for Local Development
# This file is automatically loaded when running docker-compose
# It overrides settings from docker-compose.yml for development
version: '3.9'

services:
  # API with development settings
  api:
    environment:
      # Development-specific settings
      DEBUG: "true"
      RELOAD: "true"
      LOG_LEVEL: DEBUG
    volumes:
      # Additional mounts for development
      - ./tests:/app/tests:ro
      - ./scripts:/app/scripts:ro
    command: |
      python -m uvicorn services.api.main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload 
      --reload-dir /app/services/api 
      --reload-dir /app/libs

  # Ingestion with debug settings
  ingestion:
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      WORKER_CONCURRENCY: 1  # Lower for development
    volumes:
      - ./tests:/app/tests:ro

  # Retrieval with debug settings
  retrieval:
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      CACHE_TTL_SECONDS: 60  # Shorter cache for development
    volumes:
      - ./tests:/app/tests:ro
    command: |
      python -m uvicorn services.retrieval.main:app 
      --host 0.0.0.0 
      --port 8001 
      --reload 
      --reload-dir /app/services/retrieval 
      --reload-dir /app/libs

  # Summarizer with debug settings
  summarizer:
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      BATCH_SIZE: 2  # Smaller batch for development
    volumes:
      - ./tests:/app/tests:ro
    command: |
      python -m uvicorn services.summarizer.main:app 
      --host 0.0.0.0 
      --port 8002 
      --reload 
      --reload-dir /app/services/summarizer 
      --reload-dir /app/libs
