# Minimal Docker Compose for RightLine MVP
# Only what's absolutely necessary: API + PostgreSQL with pgvector
version: '3.8'

services:
  # PostgreSQL with pgvector extension for RAG
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rightline-postgres
    restart: always
    environment:
      POSTGRES_DB: rightline
      POSTGRES_USER: rightline
      POSTGRES_PASSWORD: rightline
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rightline -d rightline"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - rightline-net

  # FastAPI Application (single service)
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    image: rightline/api:mvp
    container_name: rightline-api
    restart: always
    ports:
      - "8000:8000"  # Change to "80:8000" for production
    environment:
      # Core settings
      RIGHTLINE_APP_ENV: ${RIGHTLINE_APP_ENV:-development}
      RIGHTLINE_SECRET_KEY: ${RIGHTLINE_SECRET_KEY}
      RIGHTLINE_DATABASE_URL: postgresql://rightline:rightline@postgres:5432/rightline
      RIGHTLINE_LOG_LEVEL: ${RIGHTLINE_LOG_LEVEL:-INFO}
      # Local LLM (llama.cpp)
      RIGHTLINE_LLM_MODEL_PATH: ${RIGHTLINE_LLM_MODEL_PATH:-/models/tinyllama-1.1b-chat.Q4_K_M.gguf}
      RIGHTLINE_LLM_MAX_TOKENS: ${RIGHTLINE_LLM_MAX_TOKENS:-120}
      
      # WhatsApp (optional)
      RIGHTLINE_WHATSAPP_VERIFY_TOKEN: ${RIGHTLINE_WHATSAPP_VERIFY_TOKEN:-}
      RIGHTLINE_WHATSAPP_ACCESS_TOKEN: ${RIGHTLINE_WHATSAPP_ACCESS_TOKEN:-}
      
      # No Redis needed for MVP - use in-memory cache
      RIGHTLINE_REDIS_URL: ""
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./models:/models
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rightline-net

networks:
  rightline-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local