# Pre-commit hooks for RightLine
# Ensures code quality and security before commits

default_language_version:
  python: python3.11

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.(md|markdown)$
      - id: end-of-file-fixer
        exclude: ^.*\.(jpg|jpeg|png|gif|ico|svg)$
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-ast
      - id: check-builtin-literals
      - id: detect-private-key

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=100]

  # Python linting and import sorting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional, --no-warn-unused-ignores]
        additional_dependencies:
          - pydantic>=2.0
          - types-redis
          - types-requests
          - types-python-jose
          - types-passlib
        exclude: ^(tests/|scripts/|docs/|setup\.py)

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-ll, -r, services/, libs/]
        exclude: ^tests/

  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: >
          (?x)^(
            .*\.lock|
            \.secrets\.baseline|
            .*\.example|
            tests/.*
          )$

  # Dependency vulnerability scanning
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: poetry run safety check
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|poetry\.lock)$

  # Conventional commits (optional - enable when needed)
  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v3.4.0
  #   hooks:
  #     - id: conventional-pre-commit
  #       stages: [commit-msg]
  #       # Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(CHANGELOG\.md|docs/.*\.md)$

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, relaxed]
        exclude: ^(.github/workflows/|k8s/)

  # Check for Python docstrings
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: ^(tests/|migrations/|scripts/)
        additional_dependencies: [toml]
        args: [--convention=google]

  # SQL linting (for migrations)
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
        files: \.(sql|SQL)$
        args: [--dialect, postgres]
      - id: sqlfluff-fix
        files: \.(sql|SQL)$
        args: [--dialect, postgres]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.13.0-beta hadolint
        files: Dockerfile.*

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$

# Configuration for specific hooks
files: ^(services|libs|tests)/
exclude: >
  (?x)^(
    .*\.egg-info/|
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    \.venv/|
    __pycache__/|
    build/|
    dist/|
    htmlcov/|
    node_modules/|
    venv/|
    .*\.pyc|
    .*\.pyo|
    .*\.orig|
    .*\.rej|
    data/.*|
    .*\.min\.js|
    .*\.min\.css
  )$
